name = "Checkout Studio Assurance"
client_id = ""
application_url = "https://checkoutapp-slsdybjx.manus.space"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_checkout_and_accounts_configurations,write_checkout_and_accounts_configurations"

[auth]
redirect_urls = ["https://checkoutapp-slsdybjx.manus.space/api/shopify/auth/callback"]
